CREATE DATABASE IF NOT EXISTS app_crud_juego
USE app_crud_juego

CREATE TABLE IF NOT EXISTS juego(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    descipcion VARCHAR(255) NOT  NULL,
    precio DECIMAL(9.2) NOT NULL,
)